[package]
name = "parquet_file"
version = "0.1.0"
authors = ["Nga Tran <nga-tran@live.com>"]
edition = "2018"

[dependencies] # In alphabetical order
arrow = { version = "5.0", features = ["prettyprint"] }
base64 = "0.13"
bytes = "1.0"
chrono = "0.4"
data_types = { path = "../data_types" }
datafusion = { path = "../datafusion" }
datafusion_util = { path = "../datafusion_util" }
futures = "0.3.7"
generated_types = { path = "../generated_types" }
internal_types = { path = "../internal_types" }
iox_object_store = { path = "../iox_object_store" }
metrics = { path = "../metrics" }
object_store = { path = "../object_store" }
observability_deps = { path = "../observability_deps" }
parquet = "5.0"
parquet-format = "2.6"
parking_lot = "0.11.1"
persistence_windows = { path = "../persistence_windows" }
prost = "0.8"
query = { path = "../query" }
snafu = "0.6"
tempfile = "3.1.0"
thrift = "0.13"
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread", "sync"] }
tokio-stream = "0.1"
tracker = { path = "../tracker" }
uuid = { version = "0.8", features = ["serde", "v4"] }

[dev-dependencies]
arrow_util = { path = "../arrow_util" }
test_helpers = { path = "../test_helpers" }
