[package]
name = "iox_object_store"
version = "0.1.0"
edition = "2018"
description = "IOx-specific semantics wrapping the general-purpose object store crate"

[dependencies]
bytes = "1.0"
data_types = { path = "../data_types" }
futures = "0.3"
object_store = { path = "../object_store" }
